### ISSUE TITLE
Can't be installed on this machine

### ISSUE THREAD

**Issue by mekhaelt** [mikepowell/streamdeck-commandline#4]
I tried downloading the plugin, however I got the above message and another message saying that it is not a valid custom action. Is this plugin compatible with Macs? I'm thinking that could be the issue

**Comment by aczekajski** [comment]
It says it's a Windows commandline plugin so definitely not going to work on Mac 😅

**Comment by mikepowell** [comment]
@aczekajski is correct, this plugin is Windows only.
