### ISSUE TITLE
Knob control - stream deck +

### ISSUE THREAD

**Issue by IU4JNR** [mikepowell/streamdeck-commandline#5]
##
Could be a nice enhancement to implement the instructions to have the SD+ rotary encoder works with Thetis. To assign volume, microphone and all the variable controls, to tune xit and rit and all the controls that can be assigned to rotary encoders.

**Comment by mikepowell** [comment]
This is a nice idea but unfortunately I no longer have a Stream Deck device and I'm not actively maintaining/improving this code. Feel free to fork and implement though!
